# fly.toml app configuration file generated for ttcloneapi on 2023-07-29T17:04:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ttcloneapi"
primary_region = "syd"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
